### PR TITLE
Milestone: Friendship v2

### PR DESCRIPTION
**Pull request by mohammadumar28**
We accidentally merged the last branch which had the code of the 3rd Milestone: Friendship v2, and we have reverted the changes made to the development branch. Kindly take this pull request for Milestone 3. You can take a look into the merged branch: `friendship-v2`.

## Create Mutual Friendship

- [x] Create 2 tables when a friend request is sent by a user.

- [x] Create appropriate associations.

- [x] Style the website (users' page, navbar, etc).

### CODE REVIEW

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello,

Thank you for the improvement 
However, its still not working

Here is what we have when wanting to respond to a friendship request
Screenshot at 2020-10-15 17:34:00
There is no button to respond to the friendship request. 
Kindly put a button there, please, and make it works.

You can reach me on Slack if you want help.

Once done submit a new code review request
Thanks

Mael FOSSO

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Hi team! Well done so far! There is a core requirement for this milestone that I'd like you to consider in order to complete this milestone:
- [x] when a friendship is confirmed, there should be an additional row with reversed user-friend pair created in the friendship table. This should enable you to refactor some of your queries e.g. finding a user's friends only by `user_id` in the friendships table.

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello,

Thank you for making the suggested changes
However, there is some issues to solve

1. RSpec generate some errors
Screenshot at 2020-10-16 11:52:15

Kindly make your tests work and submit a new code review request
Thanks

Mael FOSSO

**Comment by Dandush03** [comment]
# Status: Approved :rocket: 
### Great Work, Keep it up!
# Happy Coding :tophat: :muscle:

**Pull request merged**
